import type { AppointmentLetterData } from '../types/appointment';

export const ENGLISH_SAMPLE_DATA: AppointmentLetterData = {
  company: {
    name: 'Nexus Innovation Technologies Ltd.',
    tagline: 'Empowering Next-Gen Enterprise Solutions',
    address: 'Level 12, Tech Tower, Gulshan-2',
    city: 'Dhaka - 1212',
    country: 'Bangladesh',
    phone: '+880 2-9884021',
    email: 'hr@nexustech.com',
    website: 'www.nexustech.com',
    taxId: 'BIN: 002948192-0101',
    signatoryName: 'Rafiqul Islam',
    signatoryTitle: 'Head of Human Resources',
    logoUrl: '', // Can be loaded via demo preset or user upload
    signatureUrl: '',
  },
  employee: {
    name: 'Tanvir Ahmed',
    address: 'House #45, Road #10, Sector #4, Uttara, Dhaka',
    email: 'tanvir.ahmed@example.com',
    phone: '+880 1712-345678',
    employeeId: 'EMP-2026-084',
    designation: 'Senior Full Stack Software Engineer',
    department: 'Engineering & Product Development',
    workLocation: 'Dhaka Headquarters (Hybrid)',
    employmentType: 'Full-Time',
    issueDate: '2026-08-10',
    joiningDate: '2026-09-01',
    reportingManager: 'Syed Mahbubur Rahman (VP of Engineering)',
    probationPeriod: '6 Months',
    noticePeriod: '30 Days',
  },
  compensation: {
    currency: 'BDT (৳)',
    currencySymbol: '৳',
    baseSalary: 120000,
    salaryFrequency: 'monthly',
    showTable: true,
    components: [
      { id: '1', name: 'House Rent Allowance (HRA)', amount: 48000, type: 'allowance' },
      { id: '2', name: 'Medical Allowance', amount: 12000, type: 'allowance' },
      { id: '3', name: 'Conveyance & Transport Allowance', amount: 8000, type: 'allowance' },
      { id: '4', name: 'Special Skill Allowance', amount: 12000, type: 'allowance' },
      { id: '5', name: 'Provident Fund Contribution (Deduction)', amount: 10000, type: 'deduction' },
    ],
  },
  customSubject: 'LETTER OF APPOINTMENT FOR THE POSITION OF SENIOR FULL STACK SOFTWARE ENGINEER',
  customGreeting: 'Dear Tanvir,',
  customClosing: 'We look forward to welcoming you to Nexus Innovation Technologies and building great products together.',
  clauses: [
    {
      id: 'c1',
      title: '1. Position and Role Responsibilities',
      content: 'You will be appointed as Senior Full Stack Software Engineer under the Engineering & Product Development department. You will report to Syed Mahbubur Rahman (VP of Engineering) and perform duties prescribed by the management.',
    },
    {
      id: 'c2',
      title: '2. Probationary Period & Confirmation',
      content: 'You will be on a probationary period of 6 Months from your date of joining. Upon successful completion and evaluation of your performance, your employment will be confirmed in writing.',
    },
    {
      id: 'c3',
      title: '3. Working Hours & Code of Conduct',
      content: 'Our standard working schedule is Sunday to Thursday, 9:00 AM to 6:00 PM. You are expected to strictly observe company guidelines, workplace integrity, and cybersecurity policies.',
    },
    {
      id: 'c4',
      title: '4. Confidentiality & Non-Disclosure',
      content: 'You shall maintain strict confidentiality regarding all proprietary source code, intellectual property, client datasets, business strategy, and trade secrets during and after your employment.',
    },
    {
      id: 'c5',
      title: '5. Termination & Notice Period',
      content: 'During the probation period, either party may terminate employment with 15 days written notice. Post-confirmation, a written notice of 30 Days or equivalent salary in lieu thereof is required.',
    },
  ],
  style: {
    templateId: 'corporate',
    primaryColor: '#1d4ed8',
    fontFamily: 'sans',
    fontSize: 'base',
    showWatermark: true,
    showStamp: false,
    showHeaderLine: true,
    language: 'en',
  },
};

export const BANGLA_SAMPLE_DATA: AppointmentLetterData = {
  company: {
    name: 'প্রগতি কনসালটিং ও টেকনোলজিস লিঃ',
    tagline: 'আধুনিক স্মার্ট বিজনেস সলিউশনস',
    address: 'লেভেল ৮, রূপায়ন টাওয়ার, মহাখালী সি/এ',
    city: 'ঢাকা - ১২১২',
    country: 'বাংলাদেশ',
    phone: '+৮৮০ ২-৯৮৮১৫০০',
    email: 'hr@progatitech.com.bd',
    website: 'www.progatitech.com.bd',
    taxId: 'বিন: ০০০৭৮৯১২৩-০১',
    signatoryName: 'ফারহান আহমেদ',
    signatoryTitle: 'ব্যবস্থাপনা পরিচালক ও এইচআর প্রধান',
    logoUrl: '',
    signatureUrl: '',
  },
  employee: {
    name: 'মোঃ শরিফুল ইসলাম',
    address: 'বাসা #১২, রোড #০৫, ব্লক-সি, বনশ্রী, রামপুরা, ঢাকা',
    email: 'shariful.islam@example.com',
    phone: '+৮৮০ ১৮১৯-৯৮৭৬৫৪',
    employeeId: 'পিটি-২০২৬-১১২',
    designation: 'সিনিয়র বিজনেস ডেভেলপমেন্ট ম্যানেজার',
    department: 'সেলস ও কর্পোরেট রিলেশনস',
    workLocation: 'ঢাকা প্রধান কার্যালয়',
    employmentType: 'ফুল-টাইম',
    issueDate: '২০২৬-০৮-১০',
    joiningDate: '২০২৬-০৯-০১',
    reportingManager: 'ফারহান আহমেদ (ব্যবস্থাপনা পরিচালক)',
    probationPeriod: '৬ মাস',
    noticePeriod: '৩০ দিন',
  },
  compensation: {
    currency: 'BDT (৳)',
    currencySymbol: '৳',
    baseSalary: 95000,
    salaryFrequency: 'monthly',
    showTable: true,
    components: [
      { id: '1', name: 'বাড়ি ভাড়া ভাতা (HRA)', amount: 38000, type: 'allowance' },
      { id: '2', name: 'চিকিৎসা ভাতা', amount: 10000, type: 'allowance' },
      { id: '3', name: 'যাতায়াত ভাতা', amount: 7000, type: 'allowance' },
      { id: '4', name: 'বিশেষ পারফরম্যান্স ভাতা', amount: 10000, type: 'allowance' },
      { id: '5', name: 'প্রভিডেন্ট ফান্ড কর্তন', amount: 8000, type: 'deduction' },
    ],
  },
  customSubject: 'সিনিয়র বিজনেস ডেভেলপমেন্ট ম্যানেজার পদে নিয়োগপত্র প্রদান প্রসঙ্গে।',
  customGreeting: 'জনাব শরিফুল ইসলাম,',
  customClosing: 'প্রগতি কনসালটিং ও টেকনোলজিস লিঃ পরিবারে আপনাকে স্বাগত জানাতে আমরা আন্তরিকভাবে আনন্দিত।',
  clauses: [
    {
      id: 'c1',
      title: '১. পদবী ও দায়িত্বসমূহ',
      content: 'আপনাকে প্রগতি কনসালটিং ও টেকনোলজিস লিঃ-এর সেলস ও কর্পোরেট রিলেশনস বিভাগে সিনিয়র বিজনেস ডেভেলপমেন্ট ম্যানেজার হিসেবে নিয়োগ প্রদান করা হচ্ছে। আপনি ব্যবস্থাপনা পরিচালকের অধীনে দায়িত্ব পালন করবেন।',
    },
    {
      id: 'c2',
      title: '২. শিক্ষানবিস কাল (Probation Period)',
      content: 'যোগদানের তারিখ থেকে পরবর্তী ৬ মাস আপনার শিক্ষানবিস কাল হিসেবে গণ্য হবে। সন্তোষজনক কর্মদক্ষতা ও মূল্যায়নের ভিত্তিতে আপনাকে স্থায়ীকরণ (Confirmation) পত্র প্রদান করা হবে।',
    },
    {
      id: 'c3',
      title: '৩. কর্মঘণ্টা ও নীতিমালা',
      content: 'প্রতিষ্ঠানের নির্ধারিত কর্মঘণ্টা রবিবার হতে বৃহস্পতিবার সকাল ৯:০০ টা হতে সন্ধ্যা ৬:০০ টা পর্যন্ত। প্রতিষ্ঠানের সকল শৃঙ্খলামূলক নীতি ও অভ্যন্তরীণ নিয়মকানুন মেনে চলা আবশ্যক।',
    },
    {
      id: 'c4',
      title: '৪. গোপনীয়তা রক্ষা (Confidentiality)',
      content: 'চাকরি চলাকালীন এবং পরবর্তী সময়ে কোম্পানির ব্যবসা সংক্রান্ত সকল তথ্য, ক্লায়েন্ট তালিকা, চুক্তি ও অভ্যন্তরীণ তথ্যের গোপনীয়তা রক্ষা করা আপনার আইনি দায়িত্ব।',
    },
    {
      id: 'c5',
      title: '৫. ইস্তফা ও নোটিশ পিরিয়ড',
      content: 'শিক্ষানবিস কালে উভয় পক্ষ ১৫ দিনের লিখিত নোটিশে এবং চাকরি স্থায়ীকরণের পর ১ মাসের (৩০ দিন) লিখিত নোটিশ বা সমপরিমাণ বেতন প্রদানের মাধ্যমে চুক্তি অবসান করতে পারবে।',
    },
  ],
  style: {
    templateId: 'corporate',
    primaryColor: '#047857',
    fontFamily: 'bangla',
    fontSize: 'base',
    showWatermark: true,
    showStamp: false,
    showHeaderLine: true,
    language: 'bn',
  },
};

export const FOOD_FOR_HEALTH_SAMPLE_DATA: AppointmentLetterData = {
  company: {
    name: 'FOOD FOR HEALTH',
    tagline: 'Healthy Food • Healthy Life',
    address: 'O-5,Nurjahan Road , Mohammadpur, Dhaka-1207',
    city: 'Dhaka-1207',
    country: 'Bangladesh',
    phone: '+880 1626 686555',
    email: 'foodforhealths@gmail.com',
    website: 'www.foodforhealths.com',
    signatoryName: 'Aysha',
    signatoryTitle: 'Founder',
    logoUrl: '',
    signatureUrl: '',
  },
  employee: {
    name: 'Tasfia Tanjeen',
    address: 'Mohammadpur, Dhaka',
    email: 'tasfia@example.com',
    phone: '+880 1700-000000',
    employeeId: 'FFH-2026-001',
    designation: 'Content Writer',
    department: 'Digital Marketing',
    workLocation: 'Dhaka',
    employmentType: 'Full-Time',
    issueDate: '2026-07-06',
    joiningDate: '2026-07-06',
    reportingManager: 'Management',
    probationPeriod: '3 Months',
    noticePeriod: '15 Days',
  },
  compensation: {
    currency: 'BDT',
    currencySymbol: '৳',
    baseSalary: 3000,
    salaryFrequency: 'monthly',
    showTable: false,
    components: [],
  },
  customSubject: 'LETTER OF APPOINTMENT',
  customGreeting: '',
  customOpeningParagraph: 'We are pleased to appoint you as Content Writer at Food for Health.\n\nIn this role, you will be responsible for executing all duties and responsibilities related to your position to drive our digital marketing goals.',
  customClosing: 'You are required to maintain full confidentiality regarding all company information and strategies.\n\nWe welcome you to Food for Health and wish you a successful journey with us.\n\nThank you.',
  clauses: [],
  style: {
    templateId: 'food_for_health',
    primaryColor: '#265217',
    fontFamily: 'sans',
    fontSize: 'base',
    showWatermark: false,
    showStamp: false,
    showHeaderLine: true,
    language: 'en',
  },
};

export const CREATIVE_DECORE_SAMPLE_DATA: AppointmentLetterData = {
  company: {
    name: 'CREATIVE DECORE',
    tagline: 'Exquisite Handcrafted Embroidery & Home Textiles',
    address: 'O-5,Nurjahan Road , Mohammadpur, Dhaka-1207',
    city: 'Dhaka-1207',
    country: 'Bangladesh',
    phone: '+880 1957525691',
    email: '',
    website: '',
    signatoryName: 'Tabassum',
    signatoryTitle: 'Founder',
    logoUrl: '',
    signatureUrl: '',
  },
  employee: {
    name: 'Fatema Begum',
    address: 'Mohammadpur, Dhaka',
    email: 'fatema@example.com',
    phone: '+880 1800-112233',
    employeeId: '',
    designation: 'Senior Hand Stitcher',
    department: 'Hand Stitch',
    workLocation: 'Dhaka Workshop',
    employmentType: 'Full-Time',
    issueDate: '2026-08-15',
    joiningDate: '2026-08-15',
    reportingManager: 'Head of Production',
    probationPeriod: '3 Months',
    noticePeriod: '15 Days',
  },
  compensation: {
    currency: 'BDT',
    currencySymbol: '৳',
    baseSalary: 15000,
    salaryFrequency: 'monthly',
    showTable: false,
    components: [],
  },
  customSubject: 'APPOINTMENT LETTER - CREATIVE DECORE ARTISAN TEAM',
  customGreeting: '',
  customOpeningParagraph: 'We are delighted to formally appoint you as Senior Hand Stitcher & Embroidery Artisan at Creative Decore.\n\nIn this role, you will be an integral part of our handcraft production unit, creating exquisite embroidery designs, maintaining high craftsmanship standards, and preserving traditional handcrafted art.',
  customClosing: 'We are thrilled to welcome you to the Creative Decore family and look forward to creating beautiful handcrafted products together.\n\nWarm regards,',
  clauses: [],
  style: {
    templateId: 'creative_decore',
    primaryColor: '#854d0e',
    fontFamily: 'serif',
    fontSize: 'base',
    showWatermark: false,
    showStamp: false,
    showHeaderLine: true,
    language: 'en',
  },
};

export const YAZMART_SAMPLE_DATA: AppointmentLetterData = {
  company: {
    name: 'YazMart',
    tagline: 'SHOP SMART, LIVE BETTER',
    address: '85/1, Road-04, Mohammadia Housing Society',
    city: 'Mohammadpur, Dhaka-1207',
    country: 'Bangladesh',
    phone: '+880 1628756785',
    email: 'yazmart.bd@gmail.com',
    website: 'yazmart.com',
    signatoryName: 'Faiyaz Uddin',
    signatoryTitle: 'Founder',
    logoUrl: '',
    signatureUrl: '',
  },
  employee: {
    name: 'Maharun Nesa Mira',
    address: 'Mohammadpur, Dhaka',
    email: 'maharun@example.com',
    phone: '+880 1700-000000',
    employeeId: '',
    designation: 'Content Writer',
    department: 'Digital Marketing',
    workLocation: 'Dhaka Headquarters',
    employmentType: 'Full-Time',
    issueDate: '2026-01-05',
    joiningDate: '2026-01-10',
    reportingManager: 'Faiyaz Uddin (Founder)',
    probationPeriod: '3 Months',
    noticePeriod: '15 Days',
  },
  compensation: {
    currency: 'BDT',
    currencySymbol: '৳',
    baseSalary: 18000,
    salaryFrequency: 'monthly',
    showTable: true,
    components: [
      { id: '1', name: 'Basic Salary', amount: 18000, type: 'allowance' },
    ],
  },
  customSubject: 'LETTER OF APPOINTMENT - YAZMART E-COMMERCE PLATFORM',
  customGreeting: 'Dear Maharun Nesa Mira,',
  customOpeningParagraph: 'On behalf of the executive leadership of YazMart (Multi-Vendor E-Commerce Platform), it is our privilege to formalize your appointment as Content Writer in the Digital Marketing department. As key talent in our marketplace ecosystem, your employment terms, obligations, and financial compensation plan are outlined below:',
  customClosing: 'We welcome you to YazMart and wish you a rewarding and successful journey with our team.',
  clauses: [
    {
      id: 'c1',
      title: '1. Role & Work Schedule',
      content: 'Execute assigned responsibilities in your domain for YazMart. Standard schedule: Sun-Thu, 9 AM to 6 PM.',
    },
    {
      id: 'c2',
      title: '2. Basic Salary & Sales Commission',
      content: 'Eligible for extra sales commission and bonuses based on store sales volume in addition to Basic Salary.',
    },
    {
      id: 'c3',
      title: '3. Data Confidentiality & Probation Terms',
      content: 'Maintain strict confidentiality of platform data & algorithms. IP belongs to company. 3-month probation.',
    },
  ],
  style: {
    templateId: 'yazmart',
    primaryColor: '#1d4ed8',
    fontFamily: 'sans',
    fontSize: 'base',
    showWatermark: false,
    showStamp: false,
    showHeaderLine: true,
    language: 'en',
  },
};




